In [4]:
%matplotlib inline

<div dir="rtl" lang="he" xml:lang="he">


#  טנזור - _tensor_ 🔢


טנזור (או טנסור) הוא מערך מידע הדומה מאוד לרשימות או טבלאות-_matrix_. טנזור מכיל רק מספרים והוא מיועד בעיקר לחישובים של _data sinece_. בPyTorch טנזורים משמשים גם כדאטה - הקלט והפלט של הפונקציות, וגם כפרמטרים (משקולות) לרשתות נויירונים.\
טנזורים מאוד דומים לספרייה _numpy_ . כך שמי שיודע לעבוד עם _numpy_ יתסדר בקלות עם טנזורים. ההבדל העיקרי הוא שטנזורים מיועדים לרוץ על הGPU של המחשב (שבבים גרפים), כך ניתן להריץ חישובים גדולים במהירות יחסית.  



In [3]:
import torch
import numpy as np

<div dir="rtl" lang="he" xml:lang="he">

## יצירת טנזורים ✏️ 
ניתן ליצור טנזורים בדרכים שונות, כמו שנראה בדוגמאות הבאות:

#### מדאטה 💾
ניתן להכניס את המידע לתוך הטנזור בצורה ידנית, דרך רשימה המכילה מספרים, או דרך מערך _numpy_



In [5]:
# from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
# from numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
# from another tensor


<div dir="rtl" lang="he" xml:lang="he">

#### מטנזור אחר 👨🏾‍❤️‍💋‍👨🏿

ניתן לשכפל טנזור מטנזור אחר עם הפונקציה `clone(tensor)`  
 

In [10]:
y_data = torch.clone(x_data)
print(y_data)

tensor([[1, 2],
        [3, 4]])


<div dir="rtl" lang="he" xml:lang="he">

#### טנזורים גנרים ⏹️
ניתן ליצור טנזורים ע"י פונקציות יעודייות כמו למשל - יצירת טנזור רנדומלי, טנזור אפסים או טנזור אחדות. \
צריך להעביר כפרמטר לטנזורים את המימדים  של הטנזור שרוצים ליצור 

In [11]:
shape = (2,2,2) #shape of tensor
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[[0.9910, 0.4670],
         [0.9540, 0.4880]],

        [[0.3257, 0.2431],
         [0.1457, 0.3355]]]) 

Ones Tensor: 
 tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]) 

Zeros Tensor: 
 tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


הפונקציה `()ones_like` או `()rand_like` מאפשרת ליצור טנזור של אחדות, או רנדומלי במימדים של הטנזור שעובר כפרמטר

In [12]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8822, 0.6834],
        [0.6176, 0.0503]]) 



<div dir="rtl" lang="he" xml:lang="he">

## מאפייני הטנזור  - _Tensor attributes_ 📄

מאפייני הטנזור קובעים את הגודל שלו, את סוג המספרים שהוא מכיל - _data type_ , ואת הדרך בה יעבדו אותו (CPU או GPU)  

In [12]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [13]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

<div dir="rtl" lang="he" xml:lang="he">

## אופרטורים על טנזורים - _Tensor Operations_ ➗

ישנם כ100 אופרטורים על טנזורים, הכוללים: סלייסינג, מציאת אינדקס, שיחלוף ופעולות רבות מאלגברה ליניארית. ניתן לראות את כל האופרטורים בלינק 
[כאן](https://pytorch.org/docs/stable/torch.html) 
 

כל חישובי האופרטורים יכולים להתבצע על הGPU ביעילות גבוהה יותר מחישובם על הCPU 

<div dir="rtl" lang="he" xml:lang="he">

#### גישה לאינדקס וחיתוך -  _indexing and slicing_ 

In [19]:
tensor = torch.ones(4, 4)
tensor[:,0] = 0
tensor[:,1] = 1
tensor[:,2] = 2
tensor[:,3] = 3
print(tensor)

tensor([[0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.]])


<div dir="rtl" lang="he" xml:lang="he">

#### איחוד טנזורים - _Joining tensors_
הפונקציה `cat` מאפשרת לנו לאחד כמה טנזורים לטנזור אחד, לפי המימד בו נבחר לאחד את הרשימות.

In [20]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0., 1., 2., 3., 0., 1., 2., 3., 0., 1., 2., 3.],
        [0., 1., 2., 3., 0., 1., 2., 3., 0., 1., 2., 3.],
        [0., 1., 2., 3., 0., 1., 2., 3., 0., 1., 2., 3.],
        [0., 1., 2., 3., 0., 1., 2., 3., 0., 1., 2., 3.]])


<div dir="rtl" lang="he" xml:lang="he">


#### כפל טנזורים _Multiplying tensors_
ניתן לכפול מטריצות איבר באיבר בשתי דרכים: קריאה מפורשת לפונקציה `tensor.mul`, או דרך האופרטור `*` 

In [21]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[0., 1., 4., 9.],
        [0., 1., 4., 9.],
        [0., 1., 4., 9.],
        [0., 1., 4., 9.]]) 

tensor * tensor 
 tensor([[0., 1., 4., 9.],
        [0., 1., 4., 9.],
        [0., 1., 4., 9.],
        [0., 1., 4., 9.]])


כפל מטריצות בצורה הרגילה 

In [23]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[14., 14., 14., 14.],
        [14., 14., 14., 14.],
        [14., 14., 14., 14.],
        [14., 14., 14., 14.]]) 

tensor @ tensor.T 
 tensor([[14., 14., 14., 14.],
        [14., 14., 14., 14.],
        [14., 14., 14., 14.],
        [14., 14., 14., 14.]])


<div dir="rtl" lang="he" xml:lang="he">

#### אופרטורים הפועלים על הטנזור עצמו _In-place operations_
אופרטורים שיש להם `_` לפני שם האופרטור משנים את הטנזור עליו עושים את האופרטור _In place_ 
כך ניתן לחסוך מקום בזיכרון

In [23]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


<div dir="rtl" lang="he" xml:lang="he">

### _הערה_
למרות ששימוש באופרטורים _In place_ חוסך מקום, השימוש בהם בעייתי בעת חישוב ניגזרות בגלל אובדן ההיסטוריה. (שחשוב כשעושים את הפעולות ברשת נויירונים) לכן באופן כללי מומלץ להמעיט בשימוש בהם. 

<div dir="rtl" lang="he" xml:lang="he">


### שיתוף זיכרון
טנזורים שמועובדים על הCPU וכן רכיבי `numpy` יכולים לשתף את אותו מקום בזיכרון, שינוי של המידע באחד מהם ישנה את המידע בכולם. 



In [24]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


שינוי של המידע בטנזור ישנה את המידע גם ב`numpy` 

In [25]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


הצגת מערך `numpy`  כטנזור

In [26]:
n = np.ones(5)
t = torch.from_numpy(n)

שינוי של המידע במערך ה`numpy` משנה גם הטנזור

In [27]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


<div dir="rtl" lang="he" xml:lang="he">

### צורת הטנזור
כל טנזור הוא מערך מידע ב$n$ מ
מימדים. 
על בסיס טנזור קיים ניתן בקלות לבנות טנזור שיכיל את את אותו מידע במבנה מימדים שונה. 
תצוגת הטנזור במבנה מימדים שונה נקראת `view`

t = torch.rand(5,5,5)
v = t.view(5,-1)
print(f""" 
{t.size()=},
{v.size()=},
{t[0,0,0]=},
{v[0,0]=},
{len(v)=},
{len(t)=},
 """)