In [6]:
%matplotlib inline

# תחילת השימוש בטנזורים


טנזור (או טנסור) הוא מערך מידע הדומה מאוד לרשימות או טבלאות _matrix_. טנזור מכיל רק מספרים והוא מיועד בעיקר לחישובים של _data sinece_. בPyTorch משתמשים טנזורים לקלט של דאטה, לפלט של דאטה וגם למשקלים של הדאטה.\
טנזורים מאוד דומים לספרייה _numpy_ . כך שאם אתה יודע איך לעבור עם _numpy_ רוב הכלים מאוד דומים. ההבדל העיקרי הוא שטנזורים מיודעים לרוץ על הGPU של המחשב (שבבים גרפים) וכן על חומרה יעודית. כך ניתן להריץ חישובים גדולים במהירות יחסית. 



In [7]:
import torch
import numpy as np

## יצירת טנזורים 
ניתן ליצור טנזורים בדרכים שונות, כמו שנראה בדוגמאות הבאות:

#### יצרת טנזור ישירות מהדאטא
ניתן להכניס את המידע לתוך הטנזור בצורה ידנית,למשל דרך רשימה המכילה מספרים



In [8]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

#### מתוך מערך _numpy_ 

ניתן ליצור את המערך ג"כ מתוך מערך קיים של _numpy_


In [9]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

#### ע"י טנזור אחר

ניתן לשכפל טנזור מטנזור אחר, אם לא נשנה במפורש, מאפייני הטנזור כמו הטייפ של המידע והצורה שלו יעברו מהטנזור המשוכפל.

In [10]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5317, 0.4885],
        [0.6033, 0.8579]]) 



#### ע"י פונקציות מיוחדת
ניתן ליצור טנזורים ע"י פונקציות יעודייות כמו למשל - יצירת טנזור רנדומלי, טנזור אפסים או עם אחדות. 

In [11]:
shape = (2, 3,) #shape of tensor
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0238, 0.3376, 0.4688],
        [0.8197, 0.2867, 0.2070]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


--------------




## מאפייני הטנזור _Tensor attributes_

מאפייני הטנזור קובעים את הגודל שלו, את הדאטה טייפ שלו ואת הדרך בה יעבדו אותו (CPU או GPU)  

In [12]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


--------------




In [13]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

## אופרטורים על טנזורים _Tensor Operations_

ישנם כ100 אופרטורים על טנזורים, הכוללים: סלייסינג, מציאת אינדקס, שיחלוף ופעולות רבות מאלגברה ליניארית. ניתן לראות את כל האופרטורים בלינק 
[כאן](https://pytorch.org/docs/stable/torch.html) 
 

כל חישובי האופרטורים יכולים להתבצע על הGPU ביעילות גבוהה יותר מחישובם על הCPU 

#### גישה לאינדקס וחיתוך  _indexing and slicing_ 

In [14]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### איחוד טנזורים _Joining tensors_
ע"י הפונקציה `torch.cat` ניתן לאחד טנזורים רבים לטנזור אחד, לפי המיימד בו נבחר לאחד את הרשימות. 
See also `torch.stack <https://pytorch.org/docs/stable/generated/torch.stack.html>`__,
another tensor joining op that is subtly different from ``torch.cat``.



In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


#### כפל טנזורים _Multiplying tensors_
ניתן לכפול מטריצות איבר באיבר בשתי דרכים. או  דרך קריאה מפורשת לפונקציה `tensor.mul`, או דרך האופרטור `*` 

In [ ]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

כפל מטריצות לפי לפי ההגדרה המתמטית 

In [ ]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

#### אופרטורים הפועלים על הטנזור עצמו _In-place operations_
אופרטורים שיש להם `_` לפני שם האופרטור משנים את הטנזור עליו עושים את האופרטור _In place_ 
כך ניתן לחסוך מקום בזיכרון

In [23]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


### _הערה_
למרות ששימוש באופרטורים _In place_ חוסך מקום, השימוש בהם בעייתי בעת חישוב ניגזרות בגלל אובדן ההיסטוריה. לכן באופן כללי מומלץ להמעיט בשימוש בהם. 

--------------




### שיתוף זיכרון
טנזורים שמועובדים על הCPU וכן רכיבי `numpy` יכולים לשתף את אותו מקום בזיכרון, שינוי של המידע באחד מהם ישנה את המידע בכולם. 



In [24]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


שינוי של המידע בטנזור ישנה את המידע גם ב`numpy` 

In [25]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


הצגת מערך `numpy`  כטנזור

In [26]:
n = np.ones(5)
t = torch.from_numpy(n)

שינוי של המידע במערך ה`numpy` משנה גם הטנזור

In [27]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
